src/objects/Map_Layer__c.object
<CustomObject>
    <fields>
        <fullName>KML_URL__c</fullName>
        <inlineHelpText>The URL of the KML file to load for the layer.</inlineHelpText>
        <label>KML URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Visible__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check if this Layer should be made visible for use.</inlineHelpText>
        <label>Visible</label>
        <type>Checkbox</type>
    </fields>
    <label>Map Layer</label>
    <nameField>
        <label>Map Layer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Map Layers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SautterMaps.cls
public with sharing class SautterMaps {

    public SautterMaps() {}

    ApexPages.StandardSetController mController;

    public SautterMaps(ApexPages.StandardSetController controller) {
      mController = controller;
      if (mController != null) {
        mController.setPageSize(1000);
      }
    }

    public SelectOption[] MapLayers { get {
      List<SelectOption> result = new List<SelectOption>(); 
      result.add(new SelectOption('', 'No Layer'));
      Map_Layer__c[] layers = [SELECT Name, KML_URL__c, Visible__c from Map_Layer__c];
      for (Map_Layer__c layer: layers) {
        result.add(new SelectOption(layer.KML_URL__c, layer.Name));
      }
      return result;
    } 
  }
  
 }